name: 'order_review_prediction'

version: '1.0.0'
config-version: 2

profile: 'burak-layer-profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  order_review_prediction:
      materialized: table
      staging:
        materialized: table
  