version: 2

models:
  - name: training_data
    description: This table has final training data which has combination of features based on orders and items.
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for an order

  - name: review_score_predictor
    description: AutoML Model which predicts the review score
