name: Check
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Run check
        run: make check
