name: End-to-end tests
on:
  push:
    branches: ['main']

jobs:
  check-package-loads:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Cache poetry virtualenvs
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/pypoetry/virtualenvs
          key: poetry-venvs-no-dev-${{ runner.os }}-3.8-${{ hashFiles('poetry.lock') }}
          restore-keys: poetry-vevns-no-dev-${{ runner.os }}-3.8-
      - name: Check package loads without dev dependencies
        run: make check-package-loads

  e2e-tests:
    needs: [ check-package-loads ]
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8 ]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Cache poetry virtualenvs
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/pypoetry/virtualenvs
          key: poetry-venvs-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('dbt-adapters/poetry.lock') }}
          restore-keys: poetry-venvs-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Install dbt
        run: poetry add dbt
      - name: Setup dbt Layer profile
        run: poetry run python ./workflow_scripts/setup_dbt_profile.py
      - name: Fail fast if on a fork as forks cannot run e2e-tests directly
        if: |
          github.event.pull_request.head.repo.full_name != github.repository &&
          steps.changed-files.outputs.any_changed == 'true'
        run: |
          exit 1
      - name: Run e2e-tests
        run: |
          echo ${{ secrets.BIG_QUERY_CREDENTIALS }} > test/e2e/.big_query_key
          make e2e-test